tools/makedoc.py
The arguments for Template() include a default argument with a value
of &lt;template&gt;. During doc generation, this was not being escaped causing
web browsers to stop rendering the rest of the documentation.
This fixes #243
=> Escape HTML characters when emitting documentation.

web/net.py
"not" has higher precedence over "and" operator. So, expression "not x and y" != "not x or not y".
The target is to check if any of the addr and port are invalid, but the current expression is true when addr is invalid but port is valid.
=> Fix a logical bug.

test/application.py, web/application.py
`$` allows a single line terminator before the end of the string, causing a KeyError when a route would otherwise match. This corrects the result to a “not found”.
#316 in a new branch.
=> Reject route matches ending with newlines

web/wsgi.py
parentheses are in the wrong place giving this error
```
File "/usr/local/lib/python3.4/dist-packages/web/application.py", line 341, in run
return wsgi.runwsgi(self.wsgifunc(*middleware))
File "/usr/local/lib/python3.4/dist-packages/web/wsgi.py", line 34, in runwsgi
or 'SERVER_SOFTWARE') in os.environ:
File "/usr/lib/python3.4/_collections_abc.py", line 431, in __contains__
self[key]
File "/usr/lib/python3.4/os.py", line 630, in __getitem__
value = self._data[self.encodekey(key)]
File "/usr/lib/python3.4/os.py", line 706, in encode
raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not bool
```
=> typo in fastcgi

test/requirements.txt
Using mysql-connector==2.1.4 to fix the build error in installing that library.
Installing the new versions of mysql-connector library was failing in
Travis build as that depends on protobuf which was not available.
Forcing a lower version to resolve that issue.
Closes #424
=> Fixed the travis build error caused by mysql-connector

.travis.yml
[Travis are now recommending removing __sudo__](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration)
=> Travis CI: 'sudo' is no longer required by Travis

web/net.py
Need to leave the very first line of the docstring blank to allow the markdown to render correctly whenever docstrings have multiple lines with examples.  A few functions have this issue.  If this is acceptable, I can go around and fix the rest of them up.
I considered changing makedoc.py to add the extra line but that wouldn't fix the inconsistency within within python with the help(<function_name>) variant, so decided it was better to just make the source docstrings consistent.
=> Changed docstring to fix formatting problem

web/session.py
Forcing every person (and web crawler) who visits the site to have a unique cookie means that every page is unique, and thus un-cacheable. Also, Googlebot crawling my site results in millions of sessions clogging the database, that all contain default data.
I've made a small change to web/session.py:Session._save so that it only stores sessions and sets cookies if the data is different from the initializer - with that done, I can now stick Varnish in front of the site, and it correctly serves cached pages to anonymous browsers and dynamic pages to logged-in users, drastically reducing the load.
(This is a pull-request version of #158, as requested)
=> Only store new session data if the data is non-default

web/db.py
Repeating the same fix in 35674c8cd49e29853e8728fdf5fdb4ab0da5b58a for pooled (With DBUtils) connections.
=> Fixed error in creating pooled PostgresDB with pgdb driver.

experimental/pwt.py, experimental/untwisted.py, tests/test_application.py, tests/test_browser.py
Add comment line `# fmt: off` for `urls = ()` which contain multiple patterns to bypass Black formatter.
=> Add comment line to bypass Black format if URLs contain multiple patterns.

web/browser.py, web/form.py, web/http.py, web/session.py, web/utils.py, web/webapi.py
- Remove py2.3 support
- Replace 'attr in obj.keys()' by 'attr in obj'.
- Set default cookie expire time to session timeout.
- Add support for SameSite cookie.
Fixes #521
Fixes #61 #99 #337
Fixes #409 #410 
TODO:
- Update doc to mention `samesite`: http://webpy.org/cookbook/cookies
=> Remove legacy code and improve cookie support

ChangeLog.txt, tests/test_db.py, web/db.py
Tested with MariaDB-10.1.29 on Ubuntu 18.04, and PostgreSQL-11.5 on OpenBSD 6.5.
Fixes #447
Fixes #263
=> Fixed incorrect returned insert ids with `multiple_insert()`.

experimental/pwt.py, experimental/untwisted.py
Remove an external dependency by replacing it with a module in the Python Standard Library.
=> Remove simplejson in favor of json

tests/test_session.py, web/session.py
Write the diskstore in one atomary action
This will prevent multiple threads from accessing the file and possibly
read it while it is still being written to.
Fixes #191
Fixes #182 
Fixes #83
Fixes #289
This is in essence the same as my pull request #239 from 2013 with some unittesting.
=> Fix DiskStore concurrency issue.

README.md
The Travis badge in the README was just an image. Linked it to the Travis CI page for web.py.
=> Added link to travis build status badge

web/debugerror.py
The debugerror_t was turned into a raw string in an earlier commit [[1]]
and it was using a \ in the first line as line continuation. It became a
literal \ after the string became a raw string. Fixed it by making it
into a regular string.
Fixes #555
[1]: https://github.com/webpy/webpy/commit/6bfd02668e9f56ed49f5146f42046e48263da4c1#diff-8cb9990e42dd192c282402bb2016483dR38
=> Fixed the issue with debugerror.

tests/test_db.py, web/db.py
The earlier implentation was adding an __len__ function to the result
object and that worked fine for old-style classes. With old-style
classes gone in Python 3, that started giving trouble. Fixed it by
writing a ResultSet class and a special SqliteResultSet which doesn't
support len, but supports bool.
Fixes #547.
=> Fixed the issue of len not working with the result of db query.

setup.py
https://pypi.org/project/web.py/ just has one line of text but https://pypi.org/project/tap2junit has its [README.md](https://github.com/nodejs/tap2junit/blob/master/README.md) file rendered in with links an all.
=> Render README.md into our PyPI page

web/application.py
We do not support Python 3.0, 3.1, 3.2, or 3.3
=> Drop from imp import reload for Python3 < 3.4

tests/test_wsgi.py
Old tests work on Ubuntu 18.04 (the OS used by Travis CI), but failed on OpenBSD (6.4).
This patch gets it working on both.
Thanks Kevin Lo <kevlo () openbsd ! org> for the feedback and OpenBSD port. :)
https://marc.info/?l=openbsd-ports-cvs&m=157018308915673&w=2
=> Fix unit tests in tests/test_wsgi.py.

web/debugerror.py, web/webapi.py
Subclass cgi.FieldStorage, as read_binary expects fp to return
bytes. If the headers do not contain a content-disposition with a
filename, cgi.FieldStorage's make_file will create a TemporaryFile
with `w+` flags. The write to that temporary file will fail, due to
incorrect encoding in Python 3.
See conversation in GitHub Issues:
https://github.com/webpy/webpy/issues/574
=> Subclass cgi.FieldStorage to fix POST errors.

ChangeLog.txt, web/httpserver.py, web/template.py
*) According to [PEP 0479](https://www.python.org/dev/peps/pep-0479/#writing-backwards-and-forwards-compatible-code):
> ... when `StopIteration` is raised inside a generator, it is replaced with `RuntimeError`. ...
>
> ...the change is backwards incompatible...
Close #576
Thanks @kjmph :)
*) Add `Joinedstr` in `ALLOWED_AST_NODES`.
Fixes #578
---------
To @anandology @cclauss 
Do you think we should simply replace `raise StopIteration()` by `return` in other 2 files?
- web/db.py: https://github.com/webpy/webpy/blob/master/web/db.py#L515
- web/webapi.py: https://github.com/webpy/webpy/blob/master/web/webapi.py#L636
=> Fix py3 compatibility issue.

web/utils.py
The send() method in utils.py contained a lot of functionality that could be extracted to their own methods. Including:
- Setting up connections with AWS email server
- Setting up connections with an SMTP server
By extracting this functionality the send() method is reduced from 54 lines to 14, and easier to understand. Plus, if needed in the future, other methods could use the newly created methods to create connections with the email servers and send mail.
=> Extracted Functionality from send() method in utils.py

ChangeLog.txt, test_requirements.txt, tests/test_db.py, web/db.py
As mentioned in updated ChangeLog.txt:
- Drop support for SQL driver `pgdb`. It was dead, it's mysterious that you cannot even find its website or download link. Note: The one available on [pypi](https://pypi.org/project/pgdb/) is not same as the one used in web.py. 
- Drop support for SQL driver `psycopg`. The latest version was released in 2006 (14 years ago), i doubt anyone still using `psycopg` but not `psycopg2`. Please use `psycopg2` instead.
=> Drop support for SQL drivers: pgdb, psycopg.

.github/workflows/lint_python.yml, tests/test_db.py
- Seems GitHub Actions dropped the builtin mysql service, i have to use docker image to run mysql service for testing.
- Modified `tests/test_db.py` to read MySQL host/port/db/user/pw from env variables (if not given, use pre-defined values).
Sorry for the noise of a lot GitHub Actions failures.
=> Fix github action failure: use mysql docker instead of the builtin mysql service

.github/workflows/lint_python.yml, .travis.yml, ChangeLog.txt, test_requirements.txt, tests/test_db.py, tests/test_template.py, web/application.py, web/browser.py, web/db.py, web/debugerror.py, web/http.py, web/net.py, web/py3helpers.py, web/session.py, web/template.py, web/test.py, web/utils.py, web/webapi.py
Drop py2 support:
- Remove all `if PY2:` checks.
- Remove `py3helpers.{string_types,numeric_types,text_type,imap,urljoin}`.
- Remove `decode_cookie`.
- Remove support for MySQL driver `MySQLdb`, it does not work with py3 at all.
- Disable py2 in Travis CI and GitHub Actions.
=> Drop py2: 

web/session.py, web/utils.py
=> Replace `os.rename()` by `shutil.move` for better Windows support.

web/form.py
These are frequently-needed elements on forms and currently have 90%+ browser support.
=> add Date and Time input elements

web/session.py
Fixes #644
Works with:
- MySQL column type `TEXT` and `VARBINARY`
- PostgreSQL column type `TEXT` and `bytea`
py3 code i used for testing:
```
import web
web.config.debug = False
urls = (
"/count", "count",
)
app = web.application(urls, locals())
conn = web.database(
dbn='mysql',    # Use `postgres` for PostgreSQL
host='localhost',
port=3306,    # Use `5432` for PostgreSQL
db='<db-name>',
user='<db-user>',
pw='<db-password>',
)
session = web.session.Session(
app=app,
store=web.session.DBStore(conn, "sessions"),
initializer={"count": 0},
)
class count:
def GET(self):
session.count += 1
return str(session.count)
if __name__ == "__main__":
app.run()
```
=> Fix incorrect str/bytes type of session data.

tests/test_db.py, web/db.py
=> Fixed the issue with insert returning query

test_requirements.txt, tests/test_db.py, web/application.py, web/db.py, web/py3helpers.py, web/utils.py
2 changes in this PR:
- Re-enable MySQL db driver: MySQLdb.
- pypi package name: `mysqlclient`. https://pypi.org/project/mysqlclient/
- It's a fork of old MySQLdb driver with Python 3 support,  according to GitHuB commit log, it's still under active maintenance: https://github.com/PyMySQL/mysqlclient-python/commits/master
- It's the only one mysql db driver on OpenBSD 6.7, but -snapshot branch has pymysql too.
- Drop py2 support: Remove `py3helpers.is_iter`.
=> Re-enable MySQL db driver: MySQLdb.

.github/workflows/lint_python.yml, tests/test_session.py, web/session.py
I recently experienced an issue with app using DiskStore as session store. Seems client didn't visit website for long enough to  trigger the session timeout, also the session directory was removed, when this client visit the website, web.py still tries to check the info of its seession id, since the session directory was removed, this raises exception `OSError` or `FileNotFoundError`.
This PR should fix this issue by checking session directory existence before running `os.path.listdir()`, unittest included.
=> Make sure session DiskStore `cleanup()` correctly returns when session directory was removed.

ChangeLog.txt, README.md, setup.py, web/__init__.py
setup.py: Add `python_requires='>=3.5'`
This prevents installation on legacy Python and other versions < Python 3.5 as discussed in
https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
Tasks for making a new release.
=> Release version 0.61

web/application.py, web/http.py
Because we only support python 3,  checks for Python 2 are no longer necessary.
=> Remove python2 code

web/template.py
When debugging, templates appear as `<web.template.Template instance at 0x4036ab8>` which does not aid the developer.
This PR proposes `Template(text="Template text", filename="burndown_chart.html")` instead.
=> Define a repr() for templates to ease debugging

.github/workflows/lint_python.yml, README.md, setup.py
* https://devguide.python.org/devcycle/#end-of-life-branches
* https://devguide.python.org/#status-of-python-branches
=> Start testing on Python 3.9 and stop on EOL Py3.5

web/application.py
=> Workaround for ctx.path = env.get("PATH_INFO").encode("latin1").decode("utf8")

web/application.py
There is a small typo in web/application.py.
Should read `reverse` rather than `resvere`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, resvere -> reverse

MANIFEST.in
Since version 0.61 and commit e0be57be1f032f76cbf253e960cb635239b56ec3, the official pypi tarballs don't ship `LICENSE.txt` anymore.
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> MANIFEST.in: include LICENSE.txt

setup.py, tests/test_application.py, tests/test_db.py, tests/test_wsgi.py, web/net.py, web/template.py
Warehouse now uses the project_urls provided to display links in the sidebar on [this screen](https://pypi.org/project/requests/), as well as including them in API responses to help the automation tool find the source code for Requests.
Example: [pypi.org/pypi/requests/json](https://pypi.org/pypi/requests/json)
Docs: [packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls)
=> add GitHub URL for PyPi

web/utils.py
The camelcase methods were deprecated in Python 3.10 in https://github.com/python/cpython/pull/25174
=> Set daemon attribute instead of using setDaemon method that was deprecated in Python 3.10.

MANIFEST.in
Current build will add unnecessary files, like mypy cache files, pyc files, `.DS_store` files in tests / docs folder, which will be installed on users' machine.
And the `tools` folder will be a namespace package, which will be installed on users' `site-packages`, and makes a 'tools' module which can be imported.
=> chore: remove unnecessary files in generated python package

setup.py, web/application.py, web/browser.py, web/db.py, web/debugerror.py, web/form.py, web/http.py, web/httpserver.py, web/net.py, web/session.py, web/template.py, web/utils.py, web/webapi.py
The command is `pyupgrade --keep-percent-format --py3-plus`, for we have python 3.5 and upper version support, and I think percent format is not deprecated in near future.
=> refactor: run pyupgrade on exists codes

.github/workflows/lint_python.yml
We are halfway thru the Python 3.12 alpha cycle so let's see if any of the proposed changes break our tests...
* https://peps.python.org/pep-0693/#release-schedule
* https://www.python.org/download/pre-releases
* https://www.python.org/downloads/release/python-3120a4/
=> Add Python 3.12-dev to the testing

.github/workflows/lint_python.yml, .pre-commit-config.yaml, pyproject.toml, web/application.py
[Ruff](https://beta.ruff.rs) supports [over 500 lint rules](https://beta.ruff.rs/docs/rules) including flake8, isort, pylint, and pyupgrade and is written in Rust for speed.
=> Replace flake8, isort, and pyupgrade with ruff

tests/test_db.py, web/form.py, web/template.py
Fixes #772
% `ruff --select=UP032 --fix .`
```
Found 5 errors (5 fixed, 0 remaining).
```
% `ruff rule UP032`
Derived from the **pyupgrade** linter.
Autofix is always available.
Checks for `str#format` calls that can be replaced with f-strings.
f-strings are more readable and generally preferred over `str#format` calls.
```python
"{}".format(foo)
```
Use instead:
```python
f"{foo}"
```
- [Python documentation: f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings)
- [Python f-string benchmarks](https://www.scivision.dev/python-f-string-speed)
=> ruff --select=UP032 --fix .

.pre-commit-config.yaml, ChangeLog.txt, README.md, pyproject.toml, tests/test_application.py, tools/makedoc.py, web/__init__.py, web/template.py
To see `README.md` rendered, go to https://github.com/cclauss/webpy/tree/v0.70#readme  The badges will be automatically updated when the new version lands on PyPI.
Do you see other changes since the previous version that should be added to the changelog?
* https://github.com/webpy/webpy/pulls?q=is%3Apr+is%3Aclosed
Use [ruff's pylint refactor settings](https://docs.astral.sh/ruff/settings/#pylint) to set upper limits on code complexity.
=> web.py release v0.70

tests/test_utils.py, web/utils.py, web/webapi.py
Closes #776 
This surely needs more testing. I tried to make the different commits meaningful and targeted on one thing. Specifically, 6318bfa73a086953d0a746c231e89674e4a45617 should be the one with the substantive changes (of which there are few -- it's mostly test).
I also made this responsive to some of the feedback from @tfmorris (thank you!) on #773. I have not yet make it responsive to all -- specifically the reference to `"_fieldstorage"`, which I agree should likely go.
I have been sitting on this PR for a while, though, and I want to get a draft of it in so I can perhaps get some feedback on whether this approach seems good.
I did test it with Open Library, and it works there, for whatever that is worth.
@cclauss
=> Fix storify and multipart

tests/test_session.py
Closes #783.
This PR updates the `datetime` and `timestamp` adapters for `sqlite3` in Python 3.12.
I leaned on the relevant [Open Library PR](https://github.com/internetarchive/openlibrary/pull/7827/files), however I put the code into the tests, rather than within `web.py`.
I made the changes to the tests as that's what use `sqlite3`, but perhaps they belong in `web/db.py`. For what it's worth, `web.py` doesn't currently import `sqlite3`.
Anyhow, please let me know if I should move where this code is.
Here's a before and after of running `pytest tests/test_session.py -s`:
Before:
```
INSERT INTO session (atime, data, session_id) VALUES ('2024-01-10T15:43:39.344341', 'gASVTQAAAAAAAAB9lCiMCnNlc3Npb25faWSUjCg4ODNmYjgwNGJmMGYzMWU5YWFmOTY5Zjk3ZDYz\nYTQ5NDNkZDM1ZmNilIwFY291bnSUSwGMAmlwlE51Lg==\n …
```
=> Fix: update deprecated sqlite3 datetime and timestamp adapters

pyproject.toml, requirements.txt, tests/test_template.py, web/browser.py, web/contrib/template.py, web/db.py, web/net.py, web/template.py, web/test.py
Closes #784.
This PR fixes the inability of `web.py` to parse templates on Python 3.12, and it does so by matching any unmatched `"` in a string.
In Python 3.12, changes to `tokenize.generate_tokens()` requires all quotes to be matched, and the `web.py` template parser hands unterminated strings to `tokenize.generate_tokens()` quite frequently.
This PR makes a tacit assumption that we should avoid rewriting the template parser if possible while also allowing `web.py` to parse templates on Python 3.12.
To that end, it handles every `TokenError` caused by unterminated string literals (i.e. unmatched `"` characters) by adding a `"` to the line where one is missing. Although this appears to work, I am aware that appending a `"` to each line that has an unmatched `"` is less than ideal. …
=> Fix: enable Python 3.12 to parse templates

.github/workflows/lint_python.yml, .github/workflows/release.yml, .pre-commit-config.yaml, pyproject.toml, tests/test_utils.py, tools/makedoc.py, web/__init__.py
Automate the release of web.py to PyPI on tag push. @scottbarnes 
Also, reverts the name back to web.py (instead of web-py), for historical consistency.
Furthermore, the pyproject.toml didn't include a dynamic reference to the requirements.txt, so it was missing some dependencies on install; this was corrected.
Of course, when merging, correct the name `web.py-update` back to `web.py` in both `.github/workflows/release.yml` and `pyproject.toml`...  And, correct the `web/__init__.py` to contain the desired `__version__`.
You'll need to create a new Pending Publisher in the PyPI account's https://pypi.org/manage/account/publishing/, designating the Project Name web.py, Github Owner webpy and Repository webpy, and the workflow release.yml.  Then, re-push a tag for the version you want to …
=> Automate PyPI release on new tag push

pyproject.toml, tests/test_template.py, tests/test_wsgi.py, web/py3helpers.py, web/template.py
Before this fix, it was possible to import modules from templates, which opens the possibility of RCE. This applies only when templates from untrusted users is allowed in the application. While this is not a common scenario, given the design goals of web.py templating system to be sandboxable, this is a serious flaw.
This commit fixes that issue by rejecting access to special variables with names starting with `__` at the compile time.
Fixes #801.
=> Fix: disable accessing special variables from template

web/db.py
Addresses #806
The SQL vulnerability in the previous implementation lies in the lack of validation or sanitization of the seqname parameter before it is incorporated into the SQL query. Without proper validation, an attacker could exploit this by injecting malicious SQL code into the seqname parameter, leading to a SQL Injection vulnerability.
Solution ensures that seqname only contains valid characters for SQL sequence names (letters, numbers, and underscores), and that it starts with a valid letter or underscore. This eliminates the possibility of injecting malicious SQL code.
The SQLQuery object is assumed to safely handle the sequence name as a parameter, properly escaping it or using parameterized queries to prevent SQL injection.
=> Address CVE-2025-3818

web/db.py
The `;` got dropped in the last PR, which should affect cases where seqname=True in insert_many (see: https://github.com/webpy/webpy/actions/runs/14907526277/job/41873366569) however, it should be noted that confusingly the aforementioned test sets seqname=False.
Squash on merge.
=> Fix query for #807 and #808
