webpy/webpy

web/session.py

fix for https://github.com/webpy/webpy/issues/323

fix for https://github.com/webpy/webpy/issues/323

---

web/db.py

Also added doc test for a mysql db url.

Change dburl2dict to use urlparse and add simple case.

---

web/webapi.py

An HTTP Status Code to Report Legal Obstacles
draft-tbray-http-legally-restricted-status-05
https://tools.ietf.org/html/draft-tbray-http-legally-restricted-status-05

Include Error Code `451 Unavailable For Legal Reasons`

---

web/httpserver.py
web/wsgi.py

Main part of code and modules already support it,
just check input args appropriately.
Signed-off-by: George Melikov <mail@gmelikov.ru>

wsgi: allow to run via socket

---

docs/deploying.rst

Fixed a small typo, `applicaiton` &rarr; `application`.

Fixed Typo

---

.travis.yml
test_requirements.txt

Also update the version of pytest so that Travis CI tests pass.

Travis CI: Add more flake8 tests

---

experimental/background.py
experimental/migration.py
experimental/pwt.py
experimental/untwisted.py
tests/test_application.py
tests/test_utils.py
tools/_makedoc.py
tools/makedoc.py
web/contrib/template.py
web/form.py
web/httpserver.py
web/session.py
web/template.py
web/test.py
web/wsgi.py

Used:
sed -i 's/ \+$//' **/*.py

Remove trailing whitespace

---

web/net.py

To be compatible with [twisted patched socket.inet_pton](https://github.com/twisted/twisted/blob/trunk/src/twisted/python/compat.py#L147).

catch ValueError for socket.inet_pton

---

web/form.py

Generate unique 'id' tag for web.form.Radio.

---

tests/test_db.py

Add unit tests used to verify row IDs returned by `multiple_insert()`.

---

ChangeLog.txt
web/db.py

Fixes #209
Update ChangeLog.txt.

Add support for sqlite to `web.db.dburl2dict` utility function. Doctest (with pytest) passed.

---

ChangeLog.txt
web/form.py

Allow HTML5 form input elements in `web.form.Input()`. doctest passed.

---

ChangeLog.txt
web/form.py

Fixed not correctly render the `id` attribute after changed.

---

.travis.yml
ChangeLog.txt
pyproject.toml
requirements.txt
setup.py
tools/makedoc.py
web/utils.py

Don't relay on markdown.

---

ChangeLog.txt
web/db.py

- Support tuple/set in `_sqllist()` and `sqlquote()`.
- Remove imported by unused module name.

Support tuple/set in `_sqllist()` and `sqlquote()`.

---

.travis.yml
ChangeLog.txt
tests/test_db.py
tools/makedoc.py
web/db.py
web/form.py
web/template.py
web/utils.py
web/webapi.py

https://github.com/codespell-project/codespell

Travis CI: Add codespell to detect typos

---

web/webapi.py

Fixed: not support SameSite=None.

---

web/template.py

Fixed incorrect AST Node name: Joinedstr -> JoinedStr. Fixes #578

Fixed incorrect AST Node name: Joinedstr -> JoinedStr.

---

ChangeLog.txt
tests/test_session.py
web/session.py

Add MemoryStore with simple unittest.

---

.github/workflows/lint_python.yml
web/db.py
web/debugerror.py

As discussed at https://github.com/webpy/webpy/issues/587#issuecomment-595049821
isort is run in _allow failures_ mode.

Add a GitHub  Action to lint and test Python code

---

.github/workflows/lint_python.yml
docs/conf.py
setup.py
tests/test_application.py
tests/test_browser.py
tests/test_session.py
tests/test_template.py
tests/test_wsgi.py
tools/_makedoc.py
tools/makedoc.py
web/__init__.py
web/application.py
web/debugerror.py
web/form.py
web/session.py
web/template.py
web/test.py
web/utils.py
web/wsgi.py

https://github.com/timothycrosley/isort

Isort will sort our imports so we don't have to

---

setup.py

https://pypi.org/pypi?%3Aaction=list_classifiers

setup.py: PyPI classifier License :: Public Domain

---

.github/workflows/lint_python.yml
.pre-commit-config.yaml
.travis.yml
docs/conf.py
web/__init__.py
web/contrib/template.py
web/form.py
web/template.py
web/test.py

`flake8 --count --ignore=E203,E265,E722,E731,W503 --max-line-length=477 --show-source --statistics`
```
20    E203 whitespace before ':'
3     E265 block comment should start with '# '
16    E722 do not use bare 'except'
13    E731 do not assign a lambda expression, use a def
```

Tighten up the flake8 tests

---

setup.py
tests/test_db.py
tools/_makedoc.py
tools/makedoc.py
web/__init__.py
web/application.py
web/browser.py
web/db.py
web/httpserver.py
web/template.py
web/utils.py
web/webapi.py

- Remove `get_X` in `web/browser.py`.
- Remove `from __future__ import`.

Remove 'get_X' in 'web/browser.py'.

---

ChangeLog.txt
web/__init__.py

Bump version to 0.60.

---

MANIFEST.in

Added MANIFEST.in to include docs, tests and tools in source package.

---

web/application.py
web/browser.py
web/db.py
web/form.py
web/httpserver.py
web/session.py
web/template.py
web/utils.py
web/webapi.py

This fix is required to pass CI.

Format with the latest `black` module.

---

.gitignore

add pycharm project auto-generated file `.idea` to .gitignore
Signed-off-by: Liu Ming <hit_oak_tree@126.com>

chore: add pycharm project auto-generated file `.idea` to .gitignore

---

web/session.py

Handle both session file and directory.

---

ChangeLog.txt
web/session.py

Few session fixes:
* Fixed: can not reset session data to same value as initialized. fixes #683
* Fixed: can not set session expire time. fixes #655
* Fixed: not export session store `MemoryStore`.

Few session fixes

---

ChangeLog.txt
README.md
setup.py
web/__init__.py

Tasks for making a new release.

Release version 0.62

---

web/db.py

fixes #697
fixes se2p/pynguin#3

Remove unreachable code.

---

web/template.py

https://docs.python.org/3/library/functions.html#round useful for internetarchive/openlibrary#4370

TEMPLATE_BUILTIN_NAMES: Add Python builtin round()

---

.github/workflows/lint_python.yml
tests/test_application.py
tests/test_db.py
tests/test_wsgi.py
web/net.py
web/template.py

Run `black .` so our GitHub Actions tests pass again because that utility is no longer in beta.

Blacken the codebase

---

.github/workflows/lint_python.yml

https://dev.mysql.com/doc/relnotes/mysql/8.0/en fixes our GitHub Actions that are failing as discussed at https://github.com/webpy/webpy/pull/733#issuecomment-1198332860

Upgrade to MySQL 8.0 and Python 3.11-dev

---

.pre-commit-config.yaml
ChangeLog.txt
docs/conf.py
web/application.py

% `pre-commit autoupdate`
% `pre-commit run --all-files`
@marksmayo Your review, please.

Pre commit autoupdate

---

.github/workflows/lint_python.yml
tests/test_template.py
web/template.py

fix: pypy3 support

---

.pre-commit-config.yaml
docs/conf.py
tools/makedoc.py
web/application.py
web/browser.py
web/db.py
web/debugerror.py
web/form.py
web/httpserver.py
web/session.py
web/template.py
web/utils.py

Builds on #742 
https://pypi.org/project/pyupgrade

pre-commit: Add pyupgrade --py36-plus

---

.github/workflows/lint_python.yml
.pre-commit-config.yaml
pyproject.toml
tools/makedoc.py
web/debugerror.py
web/form.py

@marksmayo Your review, please.

pre-commit autoupdate 2023-04-20

---

README.md
requirements.txt
web/session.py
web/webapi.py

I took the changes from #769 and modified them as little as possible to get Open Library working with it. See internetarchive/openlibrary#8313.
This still needs more testing.
@tfmorris
@cclauss 
@mekarpeles

Remove cgi.FieldStorage (based on #769)

---

.github/workflows/lint_python.yml
.pre-commit-config.yaml
README.md
pyproject.toml

Test on Python 3.12 and PyPy 3.10.

Upgrade GitHub Actions

---

.pre-commit-config.yaml
pyproject.toml
tests/test_form_validators.py
web/form.py

Fixes https://github.com/webpy/webpy/issues/739

Propagate field notes
